#!/usr/bin/python

import urllib2
import sys

try:
    import json
except ImportError:
    import simplejson as json

def ok(s):
    return s == "resident" or s == "virtual" or s == "mapped"


def getParsed():
    raw = urllib2.urlopen( "http://127.0.0.1:28017/_status" ).read()
    return json.loads( raw )

def data():
    parsed = getParsed()
    for k,v in parsed["serverStatus"]["mem"].iteritems():
        if ok(k):
            print( str(k) + ".value " + str(v) )

def config():

    print "graph_title MongoDB memory usage"
    print "graph_args --base 1000"
    print "graph_vlabel mb ${graph_period}"
    print "graph_category MongoDB"

    for k in getParsed()["serverStatus"]["mem"]:
        if ok( k ):
            print k + ".label " + k
            print k + ".type GAUGE"
            print k + ".draw AREA"


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        config()
    else:
        data()


