#!/usr/bin/python

import urllib2
import sys

try:
    import json
except ImportError:
    import simplejson as json


def getParsed():
    raw = urllib2.urlopen( "http://127.0.0.1:28017/_status" ).read()
    return json.loads( raw )

def data():
    parsed = getParsed()
    for k,v in parsed["serverStatus"]["opcounters"].iteritems():
        print( str(k) + ".value " + str(v) )

def config():

    print "graph_title MongoDB ops"
    print "graph_args --base 1000"
    print "graph_vlabel ops / ${graph_period}"
    print "graph_category MongoDB"
    print "graph_total total"

    for k in getParsed()["serverStatus"]["opcounters"]:
        print k + ".label " + k
        print k + ".min 0"
        print k + ".type DERIVE"
        print k + ".max 500000"
        print k + ".draw AREA"


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "config":
        config()
    else:
        data()


